name: Matrix in workflows
on: [push]

jobs:
  node-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 15, 16]
    steps:
      - name: check node versions
        run: node -v
      - name: setup-node
        uses: actions/setup-node@v3
        with:
           node-version: ${{ matrix.node-version }}
      - name: check node version after setup
        run: node -v