name: PR Comment
on:
  pull_request_target:
    types: [opened, closed, assigned]
jobs:
  pr-auto-comment:
    runs-on: ubuntu-lates
    steps:
      - name: Comment on New PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Thank You for Contributing',
            });