name: Workflow Event
on:
  workflow_run:
    workflows: [Repository Events]
    types: [completed]

jobs:
  workflow-event-triggered:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This event was triggered because 'Repository Events' workflow was completed"